Apply 4 suggestion(s) to 2 file(s)
Co-authored-by: Robert Richardson <robert.richardson@suse.com>
Co-authored-by: nicksinger <nsinger@suse.de>

diff --git a/usr/local/bin/tumblesle-fetch-jekyll b/usr/local/bin/tumblesle-fetch-jekyll
--- a/usr/local/bin/tumblesle-fetch-jekyll
+++ b/usr/local/bin/tumblesle-fetch-jekyll
@@ -1,16 +1,16 @@
 #!/bin/bash
-
+set -euo pipefail
 SECONDS_IN_MINUTE=60
 ELAPSED_DURATION_IN_SEC=$((45 * SECONDS_IN_MINUTE))
 TIMESTAMP_FILE="/tmp/timestamp.date"
 GITLAB_URL="https://gitlab.suse.de/users/sign_in"
-JEYKYLL_SRC_PATH="/srv/jekyll-source/"
+JEKYLL_SRC_PATH="/srv/jekyll-source/"
 
 HTTPCODE=$(curl $GITLAB_URL -w "%{http_code}" -s -o /dev/null)
 
 if [ "$HTTPCODE" -ge 200 ] && [ "$HTTPCODE" -le 299 ]; then
 	
-	git -C "$JEYKYLL_SRC_PATH" pull -q > /dev/null 2>&1
+	git -C "$JEKYLL_SRC_PATH" pull -q > /dev/null 2>&1
 	
 	# delete TIMESTAMP_FILE if exists, we do not want a false positive alert
 	# the next time this script runs
@@ -19,7 +19,7 @@ if [ "$HTTPCODE" -ge 200 ] && [ "$HTTPCODE" -le 299 ]; then
 else
 	# store first failure timestamp in a tmp file only if TIMESTAMP_FILE
 	# doesn't exists
-	if [ ! -s $TIMESTAMP_FILE ]; then
+	if [ ! -s "$TIMESTAMP_FILE" ]; then
 		date +%s > "$TIMESTAMP_FILE"
 	fi
 	
@@ -35,7 +35,7 @@ else
 	# and should hopefully trigger an alert via grafana
 	if [ $TIMESTAMP_DIFF -gt $ELAPSED_DURATION_IN_SEC ]; then
 		rm -f "$TIMESTAMP_FILE"
-		echo "Updating $JEYKYLL_SRC_PATH using git pull failed on $(hostname)"
+		echo "Updating $JEKYLL_SRC_PATH using git pull failed on $(hostname)"
 		echo "HTTP Resp Code from GitLab: $HTTPCODE"
 		exit 1
 	fi
